apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydration-test.fullname" . }}
  labels:
    {{- include "hydration-test.labels" . | nindent 4 }}
type: Opaque
data:
  hydration-secret-key: {{ include "common.secrets.passwords.manage" (dict "secret" "my-secret" "key" "the-password" "providedValues" (list "plainTextPassword") "context" $ "honorProvidedValues" true) }}
