apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hydration-test

helmGlobals:
  chartHome: charts/

helmCharts:
  - name: hydration-test
    version: 0.1.0
    releaseName: hydration-release
