apiVersion: v2
name: hydration-test
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: common
  version: "2.x.x"
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
    - bitnami-common
